name: Trigger auto deployment for container-app-pwysglkt6inye

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-pwysglkt6inye-AutoDeployTrigger-8f453804-22f6-4609-99c2-b238121e04ac.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPWYSGLKT6INYE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPWYSGLKT6INYE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPWYSGLKT6INYE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrypwysglkt6inye.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPPWYSGLKT6INYE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPWYSGLKT6INYE_REGISTRY_PASSWORD }}
          containerAppName: container-app-pwysglkt6inye
          resourceGroup: flarexan_alyzera
          imageToBuild: containerregistrypwysglkt6inye.azurecr.io/container-app-pwysglkt6inye:${{ github.sha }}
          dockerfilePath: Dockerfile


